/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package shopping_cidadao.fiap.evento;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;
import java.util.Optional;
@org.apache.avro.specific.AvroGenerated
public class Value extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4293655545440801669L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Value\",\"namespace\":\"shopping_cidadao.fiap.evento\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"horario\",\"type\":{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"io.debezium.time.Timestamp\"}},{\"name\":\"evento\",\"type\":\"string\"},{\"name\":\"senha\",\"type\":\"string\"},{\"name\":\"id_unidade\",\"type\":\"long\"},{\"name\":\"id_secao\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"id_guiche\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"id_categoria\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"id_prioridade\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"id_servico\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"id_atividade\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"id_atendente\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"id_motivo_cancelamento\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"id_motivo_pausa\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"id_motivo_congelamento\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"id_avaliacao\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"id_resposta\",\"type\":[\"null\",\"long\"],\"default\":null}],\"connect.name\":\"shopping_cidadao.fiap.evento.Value\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Value> ENCODER =
      new BinaryMessageEncoder<Value>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Value> DECODER =
      new BinaryMessageDecoder<Value>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Value> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Value> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Value> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Value>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Value to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Value from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Value instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Value fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long id;
   private long horario;
   private org.apache.avro.util.Utf8 evento;
   private org.apache.avro.util.Utf8 senha;
   private long id_unidade;
   private java.lang.Long id_secao;
   private java.lang.Long id_guiche;
   private java.lang.Long id_categoria;
   private java.lang.Long id_prioridade;
   private java.lang.Long id_servico;
   private java.lang.Long id_atividade;
   private java.lang.Long id_atendente;
   private java.lang.Long id_motivo_cancelamento;
   private java.lang.Long id_motivo_pausa;
   private java.lang.Long id_motivo_congelamento;
   private java.lang.Long id_avaliacao;
   private java.lang.Long id_resposta;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Value() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param horario The new value for horario
   * @param evento The new value for evento
   * @param senha The new value for senha
   * @param id_unidade The new value for id_unidade
   * @param id_secao The new value for id_secao
   * @param id_guiche The new value for id_guiche
   * @param id_categoria The new value for id_categoria
   * @param id_prioridade The new value for id_prioridade
   * @param id_servico The new value for id_servico
   * @param id_atividade The new value for id_atividade
   * @param id_atendente The new value for id_atendente
   * @param id_motivo_cancelamento The new value for id_motivo_cancelamento
   * @param id_motivo_pausa The new value for id_motivo_pausa
   * @param id_motivo_congelamento The new value for id_motivo_congelamento
   * @param id_avaliacao The new value for id_avaliacao
   * @param id_resposta The new value for id_resposta
   */
  public Value(java.lang.Long id, java.lang.Long horario, org.apache.avro.util.Utf8 evento, org.apache.avro.util.Utf8 senha, java.lang.Long id_unidade, java.lang.Long id_secao, java.lang.Long id_guiche, java.lang.Long id_categoria, java.lang.Long id_prioridade, java.lang.Long id_servico, java.lang.Long id_atividade, java.lang.Long id_atendente, java.lang.Long id_motivo_cancelamento, java.lang.Long id_motivo_pausa, java.lang.Long id_motivo_congelamento, java.lang.Long id_avaliacao, java.lang.Long id_resposta) {
    this.id = id;
    this.horario = horario;
    this.evento = evento;
    this.senha = senha;
    this.id_unidade = id_unidade;
    this.id_secao = id_secao;
    this.id_guiche = id_guiche;
    this.id_categoria = id_categoria;
    this.id_prioridade = id_prioridade;
    this.id_servico = id_servico;
    this.id_atividade = id_atividade;
    this.id_atendente = id_atendente;
    this.id_motivo_cancelamento = id_motivo_cancelamento;
    this.id_motivo_pausa = id_motivo_pausa;
    this.id_motivo_congelamento = id_motivo_congelamento;
    this.id_avaliacao = id_avaliacao;
    this.id_resposta = id_resposta;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return horario;
    case 2: return evento;
    case 3: return senha;
    case 4: return id_unidade;
    case 5: return id_secao;
    case 6: return id_guiche;
    case 7: return id_categoria;
    case 8: return id_prioridade;
    case 9: return id_servico;
    case 10: return id_atividade;
    case 11: return id_atendente;
    case 12: return id_motivo_cancelamento;
    case 13: return id_motivo_pausa;
    case 14: return id_motivo_congelamento;
    case 15: return id_avaliacao;
    case 16: return id_resposta;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: horario = (java.lang.Long)value$; break;
    case 2: evento = (org.apache.avro.util.Utf8)value$; break;
    case 3: senha = (org.apache.avro.util.Utf8)value$; break;
    case 4: id_unidade = (java.lang.Long)value$; break;
    case 5: id_secao = (java.lang.Long)value$; break;
    case 6: id_guiche = (java.lang.Long)value$; break;
    case 7: id_categoria = (java.lang.Long)value$; break;
    case 8: id_prioridade = (java.lang.Long)value$; break;
    case 9: id_servico = (java.lang.Long)value$; break;
    case 10: id_atividade = (java.lang.Long)value$; break;
    case 11: id_atendente = (java.lang.Long)value$; break;
    case 12: id_motivo_cancelamento = (java.lang.Long)value$; break;
    case 13: id_motivo_pausa = (java.lang.Long)value$; break;
    case 14: id_motivo_congelamento = (java.lang.Long)value$; break;
    case 15: id_avaliacao = (java.lang.Long)value$; break;
    case 16: id_resposta = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }

  /**
   * Gets the value of the 'id' field as an Optional<java.lang.Long>.
   * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
   */
  public Optional<java.lang.Long> getOptionalId() {
    return Optional.<java.lang.Long>ofNullable(id);
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'horario' field.
   * @return The value of the 'horario' field.
   */
  public long getHorario() {
    return horario;
  }

  /**
   * Gets the value of the 'horario' field as an Optional<java.lang.Long>.
   * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
   */
  public Optional<java.lang.Long> getOptionalHorario() {
    return Optional.<java.lang.Long>ofNullable(horario);
  }

  /**
   * Sets the value of the 'horario' field.
   * @param value the value to set.
   */
  public void setHorario(long value) {
    this.horario = value;
  }

  /**
   * Gets the value of the 'evento' field.
   * @return The value of the 'evento' field.
   */
  public org.apache.avro.util.Utf8 getEvento() {
    return evento;
  }

  /**
   * Gets the value of the 'evento' field as an Optional<org.apache.avro.util.Utf8>.
   * @return The value wrapped in an Optional&lt;org.apache.avro.util.Utf8&gt;.
   */
  public Optional<org.apache.avro.util.Utf8> getOptionalEvento() {
    return Optional.<org.apache.avro.util.Utf8>ofNullable(evento);
  }

  /**
   * Sets the value of the 'evento' field.
   * @param value the value to set.
   */
  public void setEvento(org.apache.avro.util.Utf8 value) {
    this.evento = value;
  }

  /**
   * Gets the value of the 'senha' field.
   * @return The value of the 'senha' field.
   */
  public org.apache.avro.util.Utf8 getSenha() {
    return senha;
  }

  /**
   * Gets the value of the 'senha' field as an Optional<org.apache.avro.util.Utf8>.
   * @return The value wrapped in an Optional&lt;org.apache.avro.util.Utf8&gt;.
   */
  public Optional<org.apache.avro.util.Utf8> getOptionalSenha() {
    return Optional.<org.apache.avro.util.Utf8>ofNullable(senha);
  }

  /**
   * Sets the value of the 'senha' field.
   * @param value the value to set.
   */
  public void setSenha(org.apache.avro.util.Utf8 value) {
    this.senha = value;
  }

  /**
   * Gets the value of the 'id_unidade' field.
   * @return The value of the 'id_unidade' field.
   */
  public long getIdUnidade() {
    return id_unidade;
  }

  /**
   * Gets the value of the 'id_unidade' field as an Optional<java.lang.Long>.
   * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
   */
  public Optional<java.lang.Long> getOptionalIdUnidade() {
    return Optional.<java.lang.Long>ofNullable(id_unidade);
  }

  /**
   * Sets the value of the 'id_unidade' field.
   * @param value the value to set.
   */
  public void setIdUnidade(long value) {
    this.id_unidade = value;
  }

  /**
   * Gets the value of the 'id_secao' field.
   * @return The value of the 'id_secao' field.
   */
  public java.lang.Long getIdSecao() {
    return id_secao;
  }

  /**
   * Gets the value of the 'id_secao' field as an Optional<java.lang.Long>.
   * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
   */
  public Optional<java.lang.Long> getOptionalIdSecao() {
    return Optional.<java.lang.Long>ofNullable(id_secao);
  }

  /**
   * Sets the value of the 'id_secao' field.
   * @param value the value to set.
   */
  public void setIdSecao(java.lang.Long value) {
    this.id_secao = value;
  }

  /**
   * Gets the value of the 'id_guiche' field.
   * @return The value of the 'id_guiche' field.
   */
  public java.lang.Long getIdGuiche() {
    return id_guiche;
  }

  /**
   * Gets the value of the 'id_guiche' field as an Optional<java.lang.Long>.
   * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
   */
  public Optional<java.lang.Long> getOptionalIdGuiche() {
    return Optional.<java.lang.Long>ofNullable(id_guiche);
  }

  /**
   * Sets the value of the 'id_guiche' field.
   * @param value the value to set.
   */
  public void setIdGuiche(java.lang.Long value) {
    this.id_guiche = value;
  }

  /**
   * Gets the value of the 'id_categoria' field.
   * @return The value of the 'id_categoria' field.
   */
  public java.lang.Long getIdCategoria() {
    return id_categoria;
  }

  /**
   * Gets the value of the 'id_categoria' field as an Optional<java.lang.Long>.
   * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
   */
  public Optional<java.lang.Long> getOptionalIdCategoria() {
    return Optional.<java.lang.Long>ofNullable(id_categoria);
  }

  /**
   * Sets the value of the 'id_categoria' field.
   * @param value the value to set.
   */
  public void setIdCategoria(java.lang.Long value) {
    this.id_categoria = value;
  }

  /**
   * Gets the value of the 'id_prioridade' field.
   * @return The value of the 'id_prioridade' field.
   */
  public java.lang.Long getIdPrioridade() {
    return id_prioridade;
  }

  /**
   * Gets the value of the 'id_prioridade' field as an Optional<java.lang.Long>.
   * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
   */
  public Optional<java.lang.Long> getOptionalIdPrioridade() {
    return Optional.<java.lang.Long>ofNullable(id_prioridade);
  }

  /**
   * Sets the value of the 'id_prioridade' field.
   * @param value the value to set.
   */
  public void setIdPrioridade(java.lang.Long value) {
    this.id_prioridade = value;
  }

  /**
   * Gets the value of the 'id_servico' field.
   * @return The value of the 'id_servico' field.
   */
  public java.lang.Long getIdServico() {
    return id_servico;
  }

  /**
   * Gets the value of the 'id_servico' field as an Optional<java.lang.Long>.
   * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
   */
  public Optional<java.lang.Long> getOptionalIdServico() {
    return Optional.<java.lang.Long>ofNullable(id_servico);
  }

  /**
   * Sets the value of the 'id_servico' field.
   * @param value the value to set.
   */
  public void setIdServico(java.lang.Long value) {
    this.id_servico = value;
  }

  /**
   * Gets the value of the 'id_atividade' field.
   * @return The value of the 'id_atividade' field.
   */
  public java.lang.Long getIdAtividade() {
    return id_atividade;
  }

  /**
   * Gets the value of the 'id_atividade' field as an Optional<java.lang.Long>.
   * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
   */
  public Optional<java.lang.Long> getOptionalIdAtividade() {
    return Optional.<java.lang.Long>ofNullable(id_atividade);
  }

  /**
   * Sets the value of the 'id_atividade' field.
   * @param value the value to set.
   */
  public void setIdAtividade(java.lang.Long value) {
    this.id_atividade = value;
  }

  /**
   * Gets the value of the 'id_atendente' field.
   * @return The value of the 'id_atendente' field.
   */
  public java.lang.Long getIdAtendente() {
    return id_atendente;
  }

  /**
   * Gets the value of the 'id_atendente' field as an Optional<java.lang.Long>.
   * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
   */
  public Optional<java.lang.Long> getOptionalIdAtendente() {
    return Optional.<java.lang.Long>ofNullable(id_atendente);
  }

  /**
   * Sets the value of the 'id_atendente' field.
   * @param value the value to set.
   */
  public void setIdAtendente(java.lang.Long value) {
    this.id_atendente = value;
  }

  /**
   * Gets the value of the 'id_motivo_cancelamento' field.
   * @return The value of the 'id_motivo_cancelamento' field.
   */
  public java.lang.Long getIdMotivoCancelamento() {
    return id_motivo_cancelamento;
  }

  /**
   * Gets the value of the 'id_motivo_cancelamento' field as an Optional<java.lang.Long>.
   * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
   */
  public Optional<java.lang.Long> getOptionalIdMotivoCancelamento() {
    return Optional.<java.lang.Long>ofNullable(id_motivo_cancelamento);
  }

  /**
   * Sets the value of the 'id_motivo_cancelamento' field.
   * @param value the value to set.
   */
  public void setIdMotivoCancelamento(java.lang.Long value) {
    this.id_motivo_cancelamento = value;
  }

  /**
   * Gets the value of the 'id_motivo_pausa' field.
   * @return The value of the 'id_motivo_pausa' field.
   */
  public java.lang.Long getIdMotivoPausa() {
    return id_motivo_pausa;
  }

  /**
   * Gets the value of the 'id_motivo_pausa' field as an Optional<java.lang.Long>.
   * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
   */
  public Optional<java.lang.Long> getOptionalIdMotivoPausa() {
    return Optional.<java.lang.Long>ofNullable(id_motivo_pausa);
  }

  /**
   * Sets the value of the 'id_motivo_pausa' field.
   * @param value the value to set.
   */
  public void setIdMotivoPausa(java.lang.Long value) {
    this.id_motivo_pausa = value;
  }

  /**
   * Gets the value of the 'id_motivo_congelamento' field.
   * @return The value of the 'id_motivo_congelamento' field.
   */
  public java.lang.Long getIdMotivoCongelamento() {
    return id_motivo_congelamento;
  }

  /**
   * Gets the value of the 'id_motivo_congelamento' field as an Optional<java.lang.Long>.
   * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
   */
  public Optional<java.lang.Long> getOptionalIdMotivoCongelamento() {
    return Optional.<java.lang.Long>ofNullable(id_motivo_congelamento);
  }

  /**
   * Sets the value of the 'id_motivo_congelamento' field.
   * @param value the value to set.
   */
  public void setIdMotivoCongelamento(java.lang.Long value) {
    this.id_motivo_congelamento = value;
  }

  /**
   * Gets the value of the 'id_avaliacao' field.
   * @return The value of the 'id_avaliacao' field.
   */
  public java.lang.Long getIdAvaliacao() {
    return id_avaliacao;
  }

  /**
   * Gets the value of the 'id_avaliacao' field as an Optional<java.lang.Long>.
   * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
   */
  public Optional<java.lang.Long> getOptionalIdAvaliacao() {
    return Optional.<java.lang.Long>ofNullable(id_avaliacao);
  }

  /**
   * Sets the value of the 'id_avaliacao' field.
   * @param value the value to set.
   */
  public void setIdAvaliacao(java.lang.Long value) {
    this.id_avaliacao = value;
  }

  /**
   * Gets the value of the 'id_resposta' field.
   * @return The value of the 'id_resposta' field.
   */
  public java.lang.Long getIdResposta() {
    return id_resposta;
  }

  /**
   * Gets the value of the 'id_resposta' field as an Optional<java.lang.Long>.
   * @return The value wrapped in an Optional&lt;java.lang.Long&gt;.
   */
  public Optional<java.lang.Long> getOptionalIdResposta() {
    return Optional.<java.lang.Long>ofNullable(id_resposta);
  }

  /**
   * Sets the value of the 'id_resposta' field.
   * @param value the value to set.
   */
  public void setIdResposta(java.lang.Long value) {
    this.id_resposta = value;
  }

  /**
   * Creates a new Value RecordBuilder.
   * @return A new Value RecordBuilder
   */
  public static shopping_cidadao.fiap.evento.Value.Builder newBuilder() {
    return new shopping_cidadao.fiap.evento.Value.Builder();
  }

  /**
   * Creates a new Value RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Value RecordBuilder
   */
  public static shopping_cidadao.fiap.evento.Value.Builder newBuilder(shopping_cidadao.fiap.evento.Value.Builder other) {
    if (other == null) {
      return new shopping_cidadao.fiap.evento.Value.Builder();
    } else {
      return new shopping_cidadao.fiap.evento.Value.Builder(other);
    }
  }

  /**
   * Creates a new Value RecordBuilder by copying an existing Value instance.
   * @param other The existing instance to copy.
   * @return A new Value RecordBuilder
   */
  public static shopping_cidadao.fiap.evento.Value.Builder newBuilder(shopping_cidadao.fiap.evento.Value other) {
    if (other == null) {
      return new shopping_cidadao.fiap.evento.Value.Builder();
    } else {
      return new shopping_cidadao.fiap.evento.Value.Builder(other);
    }
  }

  /**
   * RecordBuilder for Value instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Value>
    implements org.apache.avro.data.RecordBuilder<Value> {

    private long id;
    private long horario;
    private org.apache.avro.util.Utf8 evento;
    private org.apache.avro.util.Utf8 senha;
    private long id_unidade;
    private java.lang.Long id_secao;
    private java.lang.Long id_guiche;
    private java.lang.Long id_categoria;
    private java.lang.Long id_prioridade;
    private java.lang.Long id_servico;
    private java.lang.Long id_atividade;
    private java.lang.Long id_atendente;
    private java.lang.Long id_motivo_cancelamento;
    private java.lang.Long id_motivo_pausa;
    private java.lang.Long id_motivo_congelamento;
    private java.lang.Long id_avaliacao;
    private java.lang.Long id_resposta;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(shopping_cidadao.fiap.evento.Value.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.horario)) {
        this.horario = data().deepCopy(fields()[1].schema(), other.horario);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.evento)) {
        this.evento = data().deepCopy(fields()[2].schema(), other.evento);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.senha)) {
        this.senha = data().deepCopy(fields()[3].schema(), other.senha);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.id_unidade)) {
        this.id_unidade = data().deepCopy(fields()[4].schema(), other.id_unidade);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.id_secao)) {
        this.id_secao = data().deepCopy(fields()[5].schema(), other.id_secao);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.id_guiche)) {
        this.id_guiche = data().deepCopy(fields()[6].schema(), other.id_guiche);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.id_categoria)) {
        this.id_categoria = data().deepCopy(fields()[7].schema(), other.id_categoria);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.id_prioridade)) {
        this.id_prioridade = data().deepCopy(fields()[8].schema(), other.id_prioridade);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.id_servico)) {
        this.id_servico = data().deepCopy(fields()[9].schema(), other.id_servico);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.id_atividade)) {
        this.id_atividade = data().deepCopy(fields()[10].schema(), other.id_atividade);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.id_atendente)) {
        this.id_atendente = data().deepCopy(fields()[11].schema(), other.id_atendente);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.id_motivo_cancelamento)) {
        this.id_motivo_cancelamento = data().deepCopy(fields()[12].schema(), other.id_motivo_cancelamento);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.id_motivo_pausa)) {
        this.id_motivo_pausa = data().deepCopy(fields()[13].schema(), other.id_motivo_pausa);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.id_motivo_congelamento)) {
        this.id_motivo_congelamento = data().deepCopy(fields()[14].schema(), other.id_motivo_congelamento);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.id_avaliacao)) {
        this.id_avaliacao = data().deepCopy(fields()[15].schema(), other.id_avaliacao);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
      if (isValidValue(fields()[16], other.id_resposta)) {
        this.id_resposta = data().deepCopy(fields()[16].schema(), other.id_resposta);
        fieldSetFlags()[16] = other.fieldSetFlags()[16];
      }
    }

    /**
     * Creates a Builder by copying an existing Value instance
     * @param other The existing instance to copy.
     */
    private Builder(shopping_cidadao.fiap.evento.Value other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.horario)) {
        this.horario = data().deepCopy(fields()[1].schema(), other.horario);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.evento)) {
        this.evento = data().deepCopy(fields()[2].schema(), other.evento);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.senha)) {
        this.senha = data().deepCopy(fields()[3].schema(), other.senha);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.id_unidade)) {
        this.id_unidade = data().deepCopy(fields()[4].schema(), other.id_unidade);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.id_secao)) {
        this.id_secao = data().deepCopy(fields()[5].schema(), other.id_secao);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.id_guiche)) {
        this.id_guiche = data().deepCopy(fields()[6].schema(), other.id_guiche);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.id_categoria)) {
        this.id_categoria = data().deepCopy(fields()[7].schema(), other.id_categoria);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.id_prioridade)) {
        this.id_prioridade = data().deepCopy(fields()[8].schema(), other.id_prioridade);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.id_servico)) {
        this.id_servico = data().deepCopy(fields()[9].schema(), other.id_servico);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.id_atividade)) {
        this.id_atividade = data().deepCopy(fields()[10].schema(), other.id_atividade);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.id_atendente)) {
        this.id_atendente = data().deepCopy(fields()[11].schema(), other.id_atendente);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.id_motivo_cancelamento)) {
        this.id_motivo_cancelamento = data().deepCopy(fields()[12].schema(), other.id_motivo_cancelamento);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.id_motivo_pausa)) {
        this.id_motivo_pausa = data().deepCopy(fields()[13].schema(), other.id_motivo_pausa);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.id_motivo_congelamento)) {
        this.id_motivo_congelamento = data().deepCopy(fields()[14].schema(), other.id_motivo_congelamento);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.id_avaliacao)) {
        this.id_avaliacao = data().deepCopy(fields()[15].schema(), other.id_avaliacao);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.id_resposta)) {
        this.id_resposta = data().deepCopy(fields()[16].schema(), other.id_resposta);
        fieldSetFlags()[16] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }

    /**
      * Gets the value of the 'id' field as an Optional<java.lang.Long>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<java.lang.Long> getOptionalId() {
      return Optional.<java.lang.Long>ofNullable(id);
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'horario' field.
      * @return The value.
      */
    public long getHorario() {
      return horario;
    }

    /**
      * Gets the value of the 'horario' field as an Optional<java.lang.Long>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<java.lang.Long> getOptionalHorario() {
      return Optional.<java.lang.Long>ofNullable(horario);
    }

    /**
      * Sets the value of the 'horario' field.
      * @param value The value of 'horario'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setHorario(long value) {
      validate(fields()[1], value);
      this.horario = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'horario' field has been set.
      * @return True if the 'horario' field has been set, false otherwise.
      */
    public boolean hasHorario() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'horario' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearHorario() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'evento' field.
      * @return The value.
      */
    public org.apache.avro.util.Utf8 getEvento() {
      return evento;
    }

    /**
      * Gets the value of the 'evento' field as an Optional<org.apache.avro.util.Utf8>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<org.apache.avro.util.Utf8> getOptionalEvento() {
      return Optional.<org.apache.avro.util.Utf8>ofNullable(evento);
    }

    /**
      * Sets the value of the 'evento' field.
      * @param value The value of 'evento'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setEvento(org.apache.avro.util.Utf8 value) {
      validate(fields()[2], value);
      this.evento = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'evento' field has been set.
      * @return True if the 'evento' field has been set, false otherwise.
      */
    public boolean hasEvento() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'evento' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearEvento() {
      evento = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'senha' field.
      * @return The value.
      */
    public org.apache.avro.util.Utf8 getSenha() {
      return senha;
    }

    /**
      * Gets the value of the 'senha' field as an Optional<org.apache.avro.util.Utf8>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<org.apache.avro.util.Utf8> getOptionalSenha() {
      return Optional.<org.apache.avro.util.Utf8>ofNullable(senha);
    }

    /**
      * Sets the value of the 'senha' field.
      * @param value The value of 'senha'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setSenha(org.apache.avro.util.Utf8 value) {
      validate(fields()[3], value);
      this.senha = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'senha' field has been set.
      * @return True if the 'senha' field has been set, false otherwise.
      */
    public boolean hasSenha() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'senha' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearSenha() {
      senha = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'id_unidade' field.
      * @return The value.
      */
    public long getIdUnidade() {
      return id_unidade;
    }

    /**
      * Gets the value of the 'id_unidade' field as an Optional<java.lang.Long>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<java.lang.Long> getOptionalIdUnidade() {
      return Optional.<java.lang.Long>ofNullable(id_unidade);
    }

    /**
      * Sets the value of the 'id_unidade' field.
      * @param value The value of 'id_unidade'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setIdUnidade(long value) {
      validate(fields()[4], value);
      this.id_unidade = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'id_unidade' field has been set.
      * @return True if the 'id_unidade' field has been set, false otherwise.
      */
    public boolean hasIdUnidade() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'id_unidade' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearIdUnidade() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'id_secao' field.
      * @return The value.
      */
    public java.lang.Long getIdSecao() {
      return id_secao;
    }

    /**
      * Gets the value of the 'id_secao' field as an Optional<java.lang.Long>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<java.lang.Long> getOptionalIdSecao() {
      return Optional.<java.lang.Long>ofNullable(id_secao);
    }

    /**
      * Sets the value of the 'id_secao' field.
      * @param value The value of 'id_secao'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setIdSecao(java.lang.Long value) {
      validate(fields()[5], value);
      this.id_secao = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'id_secao' field has been set.
      * @return True if the 'id_secao' field has been set, false otherwise.
      */
    public boolean hasIdSecao() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'id_secao' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearIdSecao() {
      id_secao = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'id_guiche' field.
      * @return The value.
      */
    public java.lang.Long getIdGuiche() {
      return id_guiche;
    }

    /**
      * Gets the value of the 'id_guiche' field as an Optional<java.lang.Long>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<java.lang.Long> getOptionalIdGuiche() {
      return Optional.<java.lang.Long>ofNullable(id_guiche);
    }

    /**
      * Sets the value of the 'id_guiche' field.
      * @param value The value of 'id_guiche'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setIdGuiche(java.lang.Long value) {
      validate(fields()[6], value);
      this.id_guiche = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'id_guiche' field has been set.
      * @return True if the 'id_guiche' field has been set, false otherwise.
      */
    public boolean hasIdGuiche() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'id_guiche' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearIdGuiche() {
      id_guiche = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'id_categoria' field.
      * @return The value.
      */
    public java.lang.Long getIdCategoria() {
      return id_categoria;
    }

    /**
      * Gets the value of the 'id_categoria' field as an Optional<java.lang.Long>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<java.lang.Long> getOptionalIdCategoria() {
      return Optional.<java.lang.Long>ofNullable(id_categoria);
    }

    /**
      * Sets the value of the 'id_categoria' field.
      * @param value The value of 'id_categoria'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setIdCategoria(java.lang.Long value) {
      validate(fields()[7], value);
      this.id_categoria = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'id_categoria' field has been set.
      * @return True if the 'id_categoria' field has been set, false otherwise.
      */
    public boolean hasIdCategoria() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'id_categoria' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearIdCategoria() {
      id_categoria = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'id_prioridade' field.
      * @return The value.
      */
    public java.lang.Long getIdPrioridade() {
      return id_prioridade;
    }

    /**
      * Gets the value of the 'id_prioridade' field as an Optional<java.lang.Long>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<java.lang.Long> getOptionalIdPrioridade() {
      return Optional.<java.lang.Long>ofNullable(id_prioridade);
    }

    /**
      * Sets the value of the 'id_prioridade' field.
      * @param value The value of 'id_prioridade'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setIdPrioridade(java.lang.Long value) {
      validate(fields()[8], value);
      this.id_prioridade = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'id_prioridade' field has been set.
      * @return True if the 'id_prioridade' field has been set, false otherwise.
      */
    public boolean hasIdPrioridade() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'id_prioridade' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearIdPrioridade() {
      id_prioridade = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'id_servico' field.
      * @return The value.
      */
    public java.lang.Long getIdServico() {
      return id_servico;
    }

    /**
      * Gets the value of the 'id_servico' field as an Optional<java.lang.Long>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<java.lang.Long> getOptionalIdServico() {
      return Optional.<java.lang.Long>ofNullable(id_servico);
    }

    /**
      * Sets the value of the 'id_servico' field.
      * @param value The value of 'id_servico'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setIdServico(java.lang.Long value) {
      validate(fields()[9], value);
      this.id_servico = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'id_servico' field has been set.
      * @return True if the 'id_servico' field has been set, false otherwise.
      */
    public boolean hasIdServico() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'id_servico' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearIdServico() {
      id_servico = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'id_atividade' field.
      * @return The value.
      */
    public java.lang.Long getIdAtividade() {
      return id_atividade;
    }

    /**
      * Gets the value of the 'id_atividade' field as an Optional<java.lang.Long>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<java.lang.Long> getOptionalIdAtividade() {
      return Optional.<java.lang.Long>ofNullable(id_atividade);
    }

    /**
      * Sets the value of the 'id_atividade' field.
      * @param value The value of 'id_atividade'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setIdAtividade(java.lang.Long value) {
      validate(fields()[10], value);
      this.id_atividade = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'id_atividade' field has been set.
      * @return True if the 'id_atividade' field has been set, false otherwise.
      */
    public boolean hasIdAtividade() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'id_atividade' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearIdAtividade() {
      id_atividade = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'id_atendente' field.
      * @return The value.
      */
    public java.lang.Long getIdAtendente() {
      return id_atendente;
    }

    /**
      * Gets the value of the 'id_atendente' field as an Optional<java.lang.Long>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<java.lang.Long> getOptionalIdAtendente() {
      return Optional.<java.lang.Long>ofNullable(id_atendente);
    }

    /**
      * Sets the value of the 'id_atendente' field.
      * @param value The value of 'id_atendente'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setIdAtendente(java.lang.Long value) {
      validate(fields()[11], value);
      this.id_atendente = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'id_atendente' field has been set.
      * @return True if the 'id_atendente' field has been set, false otherwise.
      */
    public boolean hasIdAtendente() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'id_atendente' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearIdAtendente() {
      id_atendente = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'id_motivo_cancelamento' field.
      * @return The value.
      */
    public java.lang.Long getIdMotivoCancelamento() {
      return id_motivo_cancelamento;
    }

    /**
      * Gets the value of the 'id_motivo_cancelamento' field as an Optional<java.lang.Long>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<java.lang.Long> getOptionalIdMotivoCancelamento() {
      return Optional.<java.lang.Long>ofNullable(id_motivo_cancelamento);
    }

    /**
      * Sets the value of the 'id_motivo_cancelamento' field.
      * @param value The value of 'id_motivo_cancelamento'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setIdMotivoCancelamento(java.lang.Long value) {
      validate(fields()[12], value);
      this.id_motivo_cancelamento = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'id_motivo_cancelamento' field has been set.
      * @return True if the 'id_motivo_cancelamento' field has been set, false otherwise.
      */
    public boolean hasIdMotivoCancelamento() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'id_motivo_cancelamento' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearIdMotivoCancelamento() {
      id_motivo_cancelamento = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'id_motivo_pausa' field.
      * @return The value.
      */
    public java.lang.Long getIdMotivoPausa() {
      return id_motivo_pausa;
    }

    /**
      * Gets the value of the 'id_motivo_pausa' field as an Optional<java.lang.Long>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<java.lang.Long> getOptionalIdMotivoPausa() {
      return Optional.<java.lang.Long>ofNullable(id_motivo_pausa);
    }

    /**
      * Sets the value of the 'id_motivo_pausa' field.
      * @param value The value of 'id_motivo_pausa'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setIdMotivoPausa(java.lang.Long value) {
      validate(fields()[13], value);
      this.id_motivo_pausa = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'id_motivo_pausa' field has been set.
      * @return True if the 'id_motivo_pausa' field has been set, false otherwise.
      */
    public boolean hasIdMotivoPausa() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'id_motivo_pausa' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearIdMotivoPausa() {
      id_motivo_pausa = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'id_motivo_congelamento' field.
      * @return The value.
      */
    public java.lang.Long getIdMotivoCongelamento() {
      return id_motivo_congelamento;
    }

    /**
      * Gets the value of the 'id_motivo_congelamento' field as an Optional<java.lang.Long>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<java.lang.Long> getOptionalIdMotivoCongelamento() {
      return Optional.<java.lang.Long>ofNullable(id_motivo_congelamento);
    }

    /**
      * Sets the value of the 'id_motivo_congelamento' field.
      * @param value The value of 'id_motivo_congelamento'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setIdMotivoCongelamento(java.lang.Long value) {
      validate(fields()[14], value);
      this.id_motivo_congelamento = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'id_motivo_congelamento' field has been set.
      * @return True if the 'id_motivo_congelamento' field has been set, false otherwise.
      */
    public boolean hasIdMotivoCongelamento() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'id_motivo_congelamento' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearIdMotivoCongelamento() {
      id_motivo_congelamento = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'id_avaliacao' field.
      * @return The value.
      */
    public java.lang.Long getIdAvaliacao() {
      return id_avaliacao;
    }

    /**
      * Gets the value of the 'id_avaliacao' field as an Optional<java.lang.Long>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<java.lang.Long> getOptionalIdAvaliacao() {
      return Optional.<java.lang.Long>ofNullable(id_avaliacao);
    }

    /**
      * Sets the value of the 'id_avaliacao' field.
      * @param value The value of 'id_avaliacao'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setIdAvaliacao(java.lang.Long value) {
      validate(fields()[15], value);
      this.id_avaliacao = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'id_avaliacao' field has been set.
      * @return True if the 'id_avaliacao' field has been set, false otherwise.
      */
    public boolean hasIdAvaliacao() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'id_avaliacao' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearIdAvaliacao() {
      id_avaliacao = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'id_resposta' field.
      * @return The value.
      */
    public java.lang.Long getIdResposta() {
      return id_resposta;
    }

    /**
      * Gets the value of the 'id_resposta' field as an Optional<java.lang.Long>.
      * @return The Optional&lt;value&gt;.
      */
    public Optional<java.lang.Long> getOptionalIdResposta() {
      return Optional.<java.lang.Long>ofNullable(id_resposta);
    }

    /**
      * Sets the value of the 'id_resposta' field.
      * @param value The value of 'id_resposta'.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder setIdResposta(java.lang.Long value) {
      validate(fields()[16], value);
      this.id_resposta = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'id_resposta' field has been set.
      * @return True if the 'id_resposta' field has been set, false otherwise.
      */
    public boolean hasIdResposta() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'id_resposta' field.
      * @return This builder.
      */
    public shopping_cidadao.fiap.evento.Value.Builder clearIdResposta() {
      id_resposta = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Value build() {
      try {
        Value record = new Value();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.horario = fieldSetFlags()[1] ? this.horario : (java.lang.Long) defaultValue(fields()[1]);
        record.evento = fieldSetFlags()[2] ? this.evento : (org.apache.avro.util.Utf8) defaultValue(fields()[2]);
        record.senha = fieldSetFlags()[3] ? this.senha : (org.apache.avro.util.Utf8) defaultValue(fields()[3]);
        record.id_unidade = fieldSetFlags()[4] ? this.id_unidade : (java.lang.Long) defaultValue(fields()[4]);
        record.id_secao = fieldSetFlags()[5] ? this.id_secao : (java.lang.Long) defaultValue(fields()[5]);
        record.id_guiche = fieldSetFlags()[6] ? this.id_guiche : (java.lang.Long) defaultValue(fields()[6]);
        record.id_categoria = fieldSetFlags()[7] ? this.id_categoria : (java.lang.Long) defaultValue(fields()[7]);
        record.id_prioridade = fieldSetFlags()[8] ? this.id_prioridade : (java.lang.Long) defaultValue(fields()[8]);
        record.id_servico = fieldSetFlags()[9] ? this.id_servico : (java.lang.Long) defaultValue(fields()[9]);
        record.id_atividade = fieldSetFlags()[10] ? this.id_atividade : (java.lang.Long) defaultValue(fields()[10]);
        record.id_atendente = fieldSetFlags()[11] ? this.id_atendente : (java.lang.Long) defaultValue(fields()[11]);
        record.id_motivo_cancelamento = fieldSetFlags()[12] ? this.id_motivo_cancelamento : (java.lang.Long) defaultValue(fields()[12]);
        record.id_motivo_pausa = fieldSetFlags()[13] ? this.id_motivo_pausa : (java.lang.Long) defaultValue(fields()[13]);
        record.id_motivo_congelamento = fieldSetFlags()[14] ? this.id_motivo_congelamento : (java.lang.Long) defaultValue(fields()[14]);
        record.id_avaliacao = fieldSetFlags()[15] ? this.id_avaliacao : (java.lang.Long) defaultValue(fields()[15]);
        record.id_resposta = fieldSetFlags()[16] ? this.id_resposta : (java.lang.Long) defaultValue(fields()[16]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Value>
    WRITER$ = (org.apache.avro.io.DatumWriter<Value>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Value>
    READER$ = (org.apache.avro.io.DatumReader<Value>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeLong(this.horario);

    out.writeString(this.evento);

    out.writeString(this.senha);

    out.writeLong(this.id_unidade);

    if (this.id_secao == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.id_secao);
    }

    if (this.id_guiche == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.id_guiche);
    }

    if (this.id_categoria == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.id_categoria);
    }

    if (this.id_prioridade == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.id_prioridade);
    }

    if (this.id_servico == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.id_servico);
    }

    if (this.id_atividade == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.id_atividade);
    }

    if (this.id_atendente == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.id_atendente);
    }

    if (this.id_motivo_cancelamento == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.id_motivo_cancelamento);
    }

    if (this.id_motivo_pausa == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.id_motivo_pausa);
    }

    if (this.id_motivo_congelamento == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.id_motivo_congelamento);
    }

    if (this.id_avaliacao == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.id_avaliacao);
    }

    if (this.id_resposta == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.id_resposta);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.horario = in.readLong();

      this.evento = in.readString(this.evento);

      this.senha = in.readString(this.senha);

      this.id_unidade = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.id_secao = null;
      } else {
        this.id_secao = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.id_guiche = null;
      } else {
        this.id_guiche = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.id_categoria = null;
      } else {
        this.id_categoria = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.id_prioridade = null;
      } else {
        this.id_prioridade = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.id_servico = null;
      } else {
        this.id_servico = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.id_atividade = null;
      } else {
        this.id_atividade = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.id_atendente = null;
      } else {
        this.id_atendente = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.id_motivo_cancelamento = null;
      } else {
        this.id_motivo_cancelamento = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.id_motivo_pausa = null;
      } else {
        this.id_motivo_pausa = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.id_motivo_congelamento = null;
      } else {
        this.id_motivo_congelamento = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.id_avaliacao = null;
      } else {
        this.id_avaliacao = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.id_resposta = null;
      } else {
        this.id_resposta = in.readLong();
      }

    } else {
      for (int i = 0; i < 17; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.horario = in.readLong();
          break;

        case 2:
          this.evento = in.readString(this.evento);
          break;

        case 3:
          this.senha = in.readString(this.senha);
          break;

        case 4:
          this.id_unidade = in.readLong();
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id_secao = null;
          } else {
            this.id_secao = in.readLong();
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id_guiche = null;
          } else {
            this.id_guiche = in.readLong();
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id_categoria = null;
          } else {
            this.id_categoria = in.readLong();
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id_prioridade = null;
          } else {
            this.id_prioridade = in.readLong();
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id_servico = null;
          } else {
            this.id_servico = in.readLong();
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id_atividade = null;
          } else {
            this.id_atividade = in.readLong();
          }
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id_atendente = null;
          } else {
            this.id_atendente = in.readLong();
          }
          break;

        case 12:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id_motivo_cancelamento = null;
          } else {
            this.id_motivo_cancelamento = in.readLong();
          }
          break;

        case 13:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id_motivo_pausa = null;
          } else {
            this.id_motivo_pausa = in.readLong();
          }
          break;

        case 14:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id_motivo_congelamento = null;
          } else {
            this.id_motivo_congelamento = in.readLong();
          }
          break;

        case 15:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id_avaliacao = null;
          } else {
            this.id_avaliacao = in.readLong();
          }
          break;

        case 16:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id_resposta = null;
          } else {
            this.id_resposta = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










